In [ ]:
import os
import numpy as np
import time
import scipy
import scv
from sklearn.svm import SVC

In [ ]:
def load_train_data(data_dir):
    """
    Load training dataset from given data directory
    
    :param data_dir: data directory to load the training data
    :type data_dir: string
    :return: train images and train labels
    :rtype: Tuple of lists
    List of numpy.ndarray. shape: [num_features, dim_feature] 
    List of numpy.ndarray. shape: [num_features, 1]
    """
    
    data = np.loadtxt(data_dir, delimeter=',')
    
    train_des = data[:, :-1]
    train_label = data[:, -1]
    
    return train_des, train_label

def train_classifier(features, labels, svm_params):
    """
    Train the SVM classifier

    :param features: Features to train
    :type features: numpy.ndarray. shape: [num_features, dim_feature]
    :param labels: Labels to train
    :type labels: numpy.ndarray. shape: [num_features, 1]
    :param svm_params: SVM parameters
    :type svm_params: dict
    ['C'](float): Regularization parameter
    ['kernel'](str): Kernel specification
    :return: Trained classifier
    :rtype: sklearn.svm.SVC
    """

    svm = SVC(kernel=svm_params['kernel'], C=svm_params['C'], random_state=0)
    svm.fit(features, labels)

    return svm

# {'C': 1, 'kernel': 'rbf'} for svm_param maight be a good starting point I guess :)
# data_dir should be train_data/train_set.csv
def Trainer(svm_param, data_dir):
    """
    Train SVM models to classify new feature
      
    :param svm_params: SVM parameters
    :type svm_params: dict
    ['C'](float): Regularization parameter
    ['kernel'](str): Kernel specification
    :return: Trained classifier
    :rtype: sklearn.svm.SVC
    """
    
    # model will be saved in this directory but not implemented yet.
    if not os.path.isdir("model"):
        os.mkdir("model")
    
    start_time = time.time()
    train_des, train_label = load_train_data(data_dir)

    print('Train the classifiers...')    
    model = train_classifier(train_des, train_label, svm_params)
    
    train_accuracy = model.score(train_features, binary_labels)    
    print('Train accuracy:  {:.4f}'.format(train_accuracy))

    return model

def Predict(feat, model, cent):
    """
    Predict the label based on the trained SVM classifier
    
    :param feat: Unknown feature to classify
    :type feat: List. shape: [num_feature]
    :param model: Trained model
    :type model: sklearn.svm.SVC
    :param cent: Centroids
    :type cent: numpy.ndarray. shape: [num_centorids, dim_feature]
    :return: Correspoding Centroids with label
    :rtype: TBD
    """
    
    idx = model.predict([feat])[0]
    
    predicted_feature = cent[idx]
    
    return predicted_feature

In [5]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(a[:, :-1])
print(a[:, -1])

[[1 2 3 4]
 [6 7 8 9]]
[ 5 10]


In [8]:
a = np.array([1, 2, 3, 1, 5, 2])
a == 1

array([ True, False, False,  True, False, False])

In [10]:
from sklearn import svm
X = [[0, 0, 0, 0, 1], [1, 1, 1, 1, 1], [1, -2, 3, -1, -6]]
y = [0, 1, 2]
clf = svm.SVC()
clf.fit(X, y)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [14]:
print(clf.predict([[1, 1, 1, 1, 1]]))
print(clf.predict([[0, 0, 0, 0, 0]]))
print(clf.predict([[1, -2, 5, -2, -7]]))
print(clf.predict([[1, 1, 1, 1, 1]]))
print(clf.predict([[1, 1, 1, 1, 1]]))

[1]
[0]
[2]
[1]
[1]
